export const INPUTS_ACTION_TYPES = {
    SET_START_AMOUNT: 'SET_START_AMOUNT',
    SET_ADDITIONAL_CONTRIBUTION: 'SET_ADDITIONAL_CONTRIBUTION',
    SET_RATE_OF_RETURN: 'SET_RATE_OF_RETURN',
    SET_YEARS: 'SET_YEARS',
    SET_FREQUENCY: 'SET_FREQUENCY'
}